### ISSUE TITLE
Battery App Notifications

### ISSUE THREAD

**Issue by andrewcharnley** [sonyxperiadev/device-sony-pdx246#4]
Unsure where to file this for the Sony battery app installed on this phone, please redirect as appropriate.

This App produces many notifications, none of which can be ignored. It also emits a notification on power-plug which nullifies the option in Android (and enabled on this phone) to emit no sound on this event.

**Comment by jerpelea** [comment]
please use the bug tracker, provide screenshots with a detailed explanation and I will forward the message

**Comment by jerpelea** [comment]
https://github.com/sonyxperiadev/bug_tracker
